{{- if .Values.logSigner.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    {{- include "trillian.logSigner.labels" . | nindent 4 }}
  name: {{ template "trillian.serviceAccountName.logSigner" . }}
{{ include "common.names.namespace" . | indent 2 }}
  annotations:
{{ toYaml .Values.logSigner.serviceAccount.annotations | indent 4 }}
{{- end }}

