apiVersion: batch/v1
kind: Job
metadata:
  name: {{ template "ctlog.createtree.fullname" . }}
{{ include "ctlog.namespace" . | indent 2 }}
  labels:
    {{- include "ctlog.labels" . | nindent 4 }}
spec:
  template:
    spec:
      serviceAccountName: {{ template "ctlog.serviceAccountName.createtree" . }}
      restartPolicy: Never
      automountServiceAccountToken: {{ .Values.createtree.serviceAccount.mountToken }}
      containers:
        - name: {{ template "ctlog.createtree.fullname" . }}
          image: "{{ template "ctlog.image" .Values.createtree.image }}"
          imagePullPolicy: "{{ .Values.createtree.image.pullPolicy }}"
          env:
          - name: NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          args: ["--namespace=$(NAMESPACE)", "--configmap={{ template "ctlog.config" . }}", "--display_name={{ template "ctlog.createtree.fullname" . }}","--admin_server={{ .Values.trillian.logServer.name }}.{{ .Values.trillian.namespace }}:{{ .Values.trillian.logServer.portRPC}}"]
