apiVersion: batch/v1
kind: Job
metadata:
  name: {{ template "ctlog.createtree.fullname" . }}
{{ include "ctlog.namespace" . | indent 2 }}
  labels:
    {{- include "ctlog.labels" . | nindent 4 }}
spec:
  template:
    spec:
      serviceAccountName: {{ template "ctlog.serviceAccountName.createtree" . }}
      restartPolicy: Never
      automountServiceAccountToken: {{ .Values.createtree.serviceAccount.mountToken }}
      containers:
        - name: {{ template "ctlog.createtree.fullname" . }}
          image: "{{ template "ctlog.image" .Values.createtree.image }}"
          imagePullPolicy: "{{ .Values.createtree.image.pullPolicy }}"
          args: ["--namespace={{ include "ctlog.rawnamespace" . }}", "--configmap=ctlog-config", "--display_name=ctlogtree"]
