apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ template "ctlog.fullname" . }}-secret-operator
{{ include "ctlog.namespace" . | indent 2 }}
  labels:
    {{- include "ctlog.labels" . | nindent 4 }}
rules:
  - apiGroups: [""] # "" indicates the core API group
    resources: ["configmaps"]
    resourceNames: ["{{ template "ctlog.config" . }}"]
    verbs: ["get", "update"]
  - apiGroups: [""] # "" indicates the core API group
    resources: ["secrets"]
    verbs: ["create", "get", "update"]