{{- if .Values.mysql.enabled -}}
{{- if .Values.mysql.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    {{- include "trillian.mysql.labels" . | nindent 4 }}
  name: {{ template "trillian.serviceAccountName.mysql" . }}
{{ include "trillian.namespace" . | indent 2 }}
  annotations:
{{ toYaml .Values.mysql.serviceAccount.annotations | indent 4 }}
{{- end }}
{{- end }}

