forceNamespace: ""
imagePullSecrets: []
serviceAccountName: tuf

server:
  replicas: 1
  image:
    registry: ghcr.io
    repository: sigstore/scaffolding/server
    version: sha256:5741a5da64b17fe5667c9f4ff3003e4d7af0ba6a7c66ff752a6a7546bc05117f
    pullPolicy: IfNotPresent
  svcPort: 8080

  serviceAccount:
    create: true
    name: ""
    annotations: {}

  secrets:
    rekor:
      create: false
      name: rekor-public-key
      key: key
      path: rekor-pubkey
    fulcio:
      create: false
      name: fulcio-server-secret
      key: cert
      path: fulcio-cert
    ctlog:
      create: false
      name: ctlog-public-key
      key: public
      path: ctlog-pubkey

  ingress:
    create: true
    name: tuf-server
    className: nginx
    annotations: {}
    http:
      hosts:
      - path: /
        host: "tuf.localhost"

  service:
    type: ClusterIP
    ports:
      - name: 80-tcp
        port: 80
        protocol: TCP
        targetPort: 80



namespace:
  create: false
  name: fulcio-system
