apiVersion: v2
name: ctlog
description: Certificate Log

type: application

version: 0.1.0

keywords:
  - security
  - pki

home: https://sigstore.dev/

maintainers:
  - name: The Sigstore Authors

annotations:
  artifacthub.io/license: Apache-2.0
  artifacthub.io/images: |
    - name: ct_server
      image: gcr.io/vaikas/ct_server@sha256:935b13f5fa9646c55faf7219f26eea650aa2e509819ad6b11e41f8b4924fcaf7
    - name: createcerts
      image: gcr.io/vaikas/createcerts@sha256:516651575db19412c94d4260349a84a9c30b37b5d2635232fba669262c5cbfa6
    - name: createtree
      image: gcr.io/vaikas/createtree@sha256:4abf45842808aa35a7aa4f2058ff7629ba1c4626571e1a64667828dd1d3759ab
