apiVersion: v2
name: ctlog
description: Certificate Log

type: application

version: 0.1.0

keywords:
  - security
  - pki

home: https://sigstore.dev/

maintainers:
  - name: The Sigstore Authors

annotations:
  artifacthub.io/license: Apache-2.0
  artifacthub.io/images: |
    - name: ct_server
      image: ghcr.io/vaikas/ct_server@sha256:e3f9e14e3c12986c83f565c4cc7c6e6b208c764cf9d8bb1fac9e2450d0b0691d
    - name: createcerts
      image: ghcr.io/vaikas/createcerts@sha256:f853fc5dfd0c752142b93a6ee5d79b36aae65254cf29764a8bc654ea91c63c0d
    - name: createtree
      image: ghcr.io/vaikas/createtree@sha256:030ac4741bb73255c2b45e2b26c7350f4ce64992b74995854f92d8f617864a58
