apiVersion: v2
name: ctlog
description: Certificate Log

type: application

version: 0.1.0

keywords:
  - security
  - pki

home: https://sigstore.dev/

maintainers:
  - name: The Sigstore Authors

annotations:
  artifacthub.io/license: Apache-2.0
  artifacthub.io/images: |
    - name: ct_server
      image: ghcr.io/vaikas/ct_server@sha256:2c02400fad795693c8ccec43017d057601c62f0752d861319933c5ed463f062d
    - name: createcerts
      image: ghcr.io/sabre1041/createcerts@sha256:c615be8fe0d26309f32a1b728460b13eaf97bfc5e3c4c6c8eca03aa8ff57e497
    - name: createtree
      image: ghcr.io/vaikas/createtree@sha256:acb229e035262f8c2c6451bc96eaaa5689d62a67ac42e533d14b7f74aa2ca837
