server:
  replicaCount: 1
  image:
    registry: gcr.io
    repository: vaikas/ct_server
    pullPolicy: IfNotPresent
    # TODO
    version: "sha256:935b13f5fa9646c55faf7219f26eea650aa2e509819ad6b11e41f8b4924fcaf7"
  serviceAccount:
    create: true
    name:
    annotations: {}
    mountToken: false

createtree:
  enabled: true
  name: createtree
  image:
    registry: gcr.io
    repository: vaikas/createtree
    pullPolicy: IfNotPresent
    # TODO
    version: "sha256:4abf45842808aa35a7aa4f2058ff7629ba1c4626571e1a64667828dd1d3759ab"
  serviceAccount:
    create: true
    name:
    annotations: {}
    mountToken: true
createcerts:
  enabled: true
  replicaCount: 1
  name: createcerts
  image:
    registry: gcr.io
    repository: vaikas/createcerts
    pullPolicy: IfNotPresent
    # TODO
    version: "sha256:516651575db19412c94d4260349a84a9c30b37b5d2635232fba669262c5cbfa6"
  serviceAccount:
    create: true
    name:
    annotations: {}
    mountToken: true
# Force namespace of namespaced resources
forceNamespace: null
