namespace:
  create: false
  name: ctlog-system
server:
  replicaCount: 1
  image:
    registry: ghcr.io
    repository: vaikas/ct_server
    pullPolicy: IfNotPresent
    # TODO
    version: "sha256:2c02400fad795693c8ccec43017d057601c62f0752d861319933c5ed463f062d"
  serviceAccount:
    create: true
    name:
    annotations: {}
    mountToken: false
  service:
    type: ClusterIP
    ports:
      - name: 80-tcp
        port: 80
        protocol: TCP
        targetPort: 6962
createtree:
  enabled: true
  name: createtree
  image:
    registry: ghcr.io
    repository: vaikas/createtree
    pullPolicy: IfNotPresent
    # TODO
    version: "sha256:acb229e035262f8c2c6451bc96eaaa5689d62a67ac42e533d14b7f74aa2ca837"
  serviceAccount:
    create: true
    name:
    annotations: {}
    mountToken: true
createcerts:
  enabled: true
  replicaCount: 1
  name: createcerts
  image:
    registry: ghcr.io
    # repository: vaikas/createcerts
    repository: sabre1041/createcerts
    pullPolicy: IfNotPresent
    # TODO
    # version: "sha256:c8ea6165cd73c51adbf2b2b70897318ef934ca18554be2bc66b16cde01a6a0a6"
    version: "sha256:c615be8fe0d26309f32a1b728460b13eaf97bfc5e3c4c6c8eca03aa8ff57e497"
  serviceAccount:
    create: true
    name:
    annotations: {}
    mountToken: true
trillian:
  namespace: trillian-system
  logServer:
    name: trillian-logserver
    portRPC: 8091
# Force namespace of namespaced resources
forceNamespace: null
