namespace:
  create: false
  name: ctlog-system
server:
  replicaCount: 1
  image:
    registry: ghcr.io
    repository: sigstore/scaffolding/ct_server:v0.2.0
    pullPolicy: IfNotPresent
    # v0.2.0
    version: "sha256:b128e676903c8ade1f331ac8e0679c0af440481f20fd2dd6eb1abe59a44074de"
  serviceAccount:
    create: true
    name: ""
    annotations: {}
    mountToken: false
  service:
    type: ClusterIP
    ports:
      - name: 80-tcp
        port: 80
        protocol: TCP
        targetPort: 6962
createtree:
  enabled: true
  name: createtree
  image:
    registry: ghcr.io
    repository: sigstore/scaffolding/createtree
    pullPolicy: IfNotPresent
    # v0.2.0
    version: "sha256:de57091f8b846ad7935b1c70af0a45e55af7fed50508bec30a51f41509ae75f1"
  serviceAccount:
    create: true
    name: ""
    annotations: {}
    mountToken: true
createcerts:
  enabled: true
  replicaCount: 1
  name: createcerts
  image:
    registry: ghcr.io
    repository: sigstore/scaffolding/createcerts
    pullPolicy: IfNotPresent
    # v0.2.0
    version: "sha256:6baad7b01770798fcaa4fcdefb96217ce46fae16e33b63ac4f1af1c07b38cf19"
  serviceAccount:
    create: true
    name: ""
    annotations: {}
    mountToken: true
trillian:
  namespace: trillian-system
  logServer:
    name: trillian-logserver
    portRPC: 8091
# Force namespace of namespaced resources
forceNamespace: ""
