namespace:
  create: false
  name: fulcio-system
config:
  contents:
server:
  replicaCount: 1
  svcPort: 80
  image:
    registry: gcr.io
    repository: projectsigstore/fulcio
    pullPolicy: IfNotPresent
    # TODO
    version: "sha256:66870bd6b111f3c5478703a8fb31c062003f0127b2c2c5e49ccd82abc4ec7841"
  args:
    port: 5555
    certificateAuthority: googleca
    gcp_private_ca_parent: projects/test/locations/us-east1/caPools/test
  serviceAccount:
    create: true
    name:
    annotations: {}
    mountToken: true
  service:
    type: ClusterIP
    ports:
      - name: 80-tcp
        port: 80
        protocol: TCP
        targetPort: 5555
  ingress:
    enabled: true
    annotations: {}
    path: /
    tls: {}
createcerts:
  enabled: true
  replicaCount: 1
  name: createcerts
  image:
    registry: ghcr.io
    repository: vaikas/createcerts
    pullPolicy: IfNotPresent
    # TODO
    version: "sha256:5dd07d84546cf0036fc47c5b0aad38a185ab35c2a045ce789ca96ac2568694f3"
  serviceAccount:
    create: true
    name:
    annotations: {}
    mountToken: true
# Configure ctlog dependency
ctlog:
  enabled: true
  name: ctlog
  forceNamespace: ctlog-system
  fullnameOverride: ctlog
  namespace:
    name: ctlog-system
    create: true
  createtree:
    name: ctlog-createtree
    fullnameOverride: ctlog-createtree
  createcerts:
    name: ctlog-createcerts
    fullnameOverride: ctlog-createcerts
# Force namespace of namespaced resources
forceNamespace: null
