apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ template "common.names.fullname" . }}
{{ include "common.names.namespace" . | indent 2 }}
  labels:
    {{- include "common.labels.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ template "common.names.fullname" . }}
subjects:
  - kind: ServiceAccount
    name: {{ template "tuf.serviceAccountName" . }}