apiVersion: v1
kind: Service
metadata:
  name: {{ template "common.names.fullname" . }}
{{ include "common.names.namespace" . | indent 2 }}
  labels:
    {{- include "common.labels.labels" . | nindent 4 }}
{{- if .Values.server.service.labels }}
{{ toYaml .Values.server.service.labels | indent 4 }}
{{- end }}
spec:
  ports:
    {{- tpl (toYaml .Values.server.service.ports) . | nindent 4 }}
  selector:
    {{- include "common.labels.selectorLabels" . | nindent 4 }}
  type: ClusterIP