{{- if .Values.server.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "tuf.serviceAccountName" . }}
  labels:
    {{- include "common.labels.labels" . | nindent 4 }}
{{ include "common.names.namespace" . | indent 2 }}
  annotations:
{{ toYaml .Values.server.serviceAccount.annotations | indent 4 }}
{{- end }}
