apiVersion: v2
name: rekor
description: A Helm chart for Kubernetes

type: application

version: 0.1.2

keywords:
  - security

home: https://sigstore.dev/
sources:
  - https://github.com/sigstore/rekor
maintainers:
  - name: The Sigstore Authors
