{{- range .Values.server.ingresses }}
{{- if and (.enabled) (eq .className "gce") (.backendConfigSpec) }}
apiVersion: cloud.google.com/v1
kind: BackendConfig
metadata:
  name: {{ template "common.names.fullname" $ -}}-{{- .name }}
  labels:
    {{- include "common.labels.labels" $ | nindent 4 }}
{{ include "common.names.namespace" $ | indent 2 }}
spec:
{{ toYaml .backendConfigSpec | indent 2 }}
---
{{- end }}
{{- end }}