apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "fulcio.config" . }}
{{ include "fulcio.namespace" . | indent 2 }}
  labels:
    {{- include "fulcio.labels" . | nindent 4 }}
data:
  config.json: |-
    {
      "OIDCIssuers": {
        "https://accounts.google.com": {
          "IssuerURL": "https://accounts.google.com",
          "ClientID": "sigstore",
          "Type": "email"
        },
        "https://token.actions.githubusercontent.com": {
          "IssuerURL": "https://token.actions.githubusercontent.com",
          "ClientID": "sigstore",
          "Type": "github-workflow"
        }
      },
      "MetaIssuers": {
        "https://container.googleapis.com/v1/projects/*/locations/*/clusters/*": {
          "Type": "kubernetes",
          "ClientID": "sigstore"
        }
      }
    }
