apiVersion: v1
kind: Service
metadata:
  annotations:
{{- $backendConfigName := include "common.names.fullname" . -}}
{{ if .Values.server.service.annotations }}
{{ toYaml .Values.server.service.annotations | indent 4 }}
{{ end }}
{{- $printed := false -}}
{{- range .Values.server.ingresses }}
{{- if and (.enabled) (eq .className "gce") (not $printed) }}
  {{- if .backendConfigSpec }}
    cloud.google.com/backend-config: '{"ports": {"{{- $.Values.server.svcPort -}}":"{{- printf "%v-%v" $backendConfigName .name -}}","{{- $.Values.server.grpcSvcPort -}}":"{{- printf "%v-%v" $backendConfigName .name -}}"}}'
  {{- end }}
    cloud.google.com/neg: '{"ingress": true}'
    cloud.google.com/app-protocols: '{"grpc":"HTTP2"}'
  {{- $printed = true -}}
{{- end }}
{{- end }}
  labels:
    {{- include "common.labels.labels" . | nindent 4 }}
{{- if .Values.server.service.labels }}
{{ toYaml .Values.server.service.labels | indent 4 }}
{{- end }}
  name: {{ template "common.names.fullname" . }}
{{ include "common.names.namespace" . | indent 2 }}
spec:
  ports:
    {{- tpl (toYaml .Values.server.service.ports) . | nindent 4 }}
  selector:
    {{- include "common.labels.selectorLabels" . | nindent 4 }}
  type: "{{ .Values.server.service.type }}"
