apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "fulcio.config" . }}
{{ include "fulcio.namespace" . | indent 2 }}
  labels:
    {{- include "fulcio.labels" . | nindent 4 }}
data:
  config.json: |-
{{- range $key, $val := .Values.config.values }}
{{ $key | quote | indent 6}}: {{ $val | quote }}
{{- end}}