apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "fulcio.config" . }}
{{ include "fulcio.namespace" . | indent 2 }}
  labels:
    {{- include "fulcio.labels" . | nindent 4 }}
data:
  config.json: |-
    {
      "OIDCIssuers": {
        "https://kubernetes.default.svc": {
          "IssuerURL": "https://kubernetes.default.svc",
          "ClientID": "sigstore",
          "Type": "kubernetes"
        }
      },
      "MetaIssuers": {
        "https://kubernetes.*.svc": {
          "ClientID": "sigstore",
          "Type": "kubernetes"
        }
      }
    }