apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ template "rekor.fullname" . }}-cm-operator
{{ include "rekor.namespace" . | indent 2 }}
  labels:
    {{- include "rekor.labels" . | nindent 4 }}
rules:
  - apiGroups: [""] # "" indicates the core API group
    resources: ["configmaps"]
    resourceNames: ["{{ template "rekor.config" . }}"]
    verbs: ["get", "update"]
