apiVersion: batch/v1
kind: Job
metadata:
  labels:
    {{- include "rekor.server.labels" . | nindent 4 }}
  name: {{ template "rekor.createtree.fullname" . }}
{{ include "rekor.namespace" . | indent 2 }}
spec:
  template:
    spec:
      serviceAccountName: {{ template "rekor.serviceAccountName.createtree" . }}
      restartPolicy: Never
      automountServiceAccountToken: true
      containers:
        - name: {{ template "rekor.createtree.fullname" . }}
          image: "{{ template "rekor.image" .Values.createtree.image }}"
          args: ["--namespace=$(NAMESPACE)", "--configmap={{ template "rekor.config" . }}", "--display_name=rekortree","--admin_server={{ .Values.trillian.logServer.name }}.{{ .Values.trillian.forceNamespace }}:{{ .Values.trillian.logServer.portRPC}}"]
          env:
          - name: NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace