apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "rekor.serviceAccountName.createtree" . }}
{{ include "rekor.namespace" . | indent 2 }}
  labels:
    {{- include "rekor.server.labels" . | nindent 4 }}
  annotations:
{{ toYaml .Values.createtree.serviceAccount.annotations | indent 4 }}
