{{- if .Values.createdb.enabled }}
{{- if .Values.createdb.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    {{- include "trillian.mysql.labels" . | nindent 4 }}
  name: {{ template "trillian.serviceAccountName.createdb" . }}
{{ include "common.names.namespace" . | indent 2 }}
  annotations:
{{ toYaml .Values.createdb.serviceAccount.annotations | indent 4 }}
{{- end }}
{{- end }}
